
# PRODUCT-MANAGEMENT

@baseURL = http://localhost:8000/api/v1/products

### GET the product list

GET {{baseURL}}

### POST request
POST {{baseURL}}
Content-Type: application/json

{
      "product":"test2",
      "price": 100
}

### PATCh request

PATCH {{baseURL}}
Content-Type: application/json

{
"_id":"67b452cf3f46377cd9d2ad41",
"product":"Lichhi"
}

### Delete request

DELETE {{baseURL}}/67ac4173e8817107fccc4f7d
